name: Prettify Code

on:
  pull_request:

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-deps: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Run Prettier
        run: |
          npm i --save-dev prettier prettier-plugin-astro
          npx prettier --write **/*.{js,md,astro,ts} --tab-width 4

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'src'

          author_name: Prettier
          default_author: github_actions

          fetch: false

          message: 'Prettying'

