name: Prettier
on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: phaired/prettier_action@v0.1.6-alpha
        with:
          prettier_options: --write **/*.{js,md,astro,ts} --tab-width 4
          prettier_plugins: prettier-plugin-astro