name: Prettify Code

on:
  pull_request:

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-deps: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run Prettier
        run: |
          bun install --save-dev prettier prettier-plugin-astro
          bunx prettier --write **/*.{js,md,astro,ts} --tab-width 4

      - uses: EndBug/add-and-commit@v9
        with:
          add: "src"
          author_name: Prettier
          default_author: github_actions
          fetch: false
          message: "Prettying"
